version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
        - "/EmergencyPager"
        - "/EmergencyPager.Common"
        - "/EmergencyPager.Toast"
    schedule:
      interval: "weekly"
