<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Version="0.3.0" Include="Bom.Squad" />
        <PackageVersion Version="4.3.0" Include="IPNetwork2" />
        <PackageVersion Version="1.1.0" Include="Kasa" />
        <PackageVersion Version="10.0.10" Include="Microsoft.AspNetCore.SignalR.Client" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Hosting" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Hosting.Systemd" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Hosting.WindowsServices" />
        <PackageVersion Version="7.1.3" Include="Microsoft.Toolkit.Uwp.Notifications" />
        <PackageVersion Version="1.2.0-beta5" Include="PagerDuty" />
        <PackageVersion Version="1.2.0-beta5" Include="PagerDuty.Webhooks" />
        <PackageVersion Version="1.2.0-beta.3" Include="RuntimeUpgradeNotifier" />
        <PackageVersion Version="0.0.10" Include="SignalRClientGenerator" />
        <PackageVersion Version="10.0.10" Include="System.Drawing.Common" />
        <PackageVersion Version="3.0.0-beta6" Include="ThrottleDebounce" />
        <PackageVersion Version="0.0.1-beta.50" Include="Unfucked" />
        <PackageVersion Version="0.0.1-beta.18" Include="Unfucked.DI" />
        <PackageVersion Version="0.0.1-beta.33" Include="Unfucked.HTTP" />
    </ItemGroup>
    <ItemGroup Label="Provided by runtime to EmergencyPager" Condition="'$(_IsPublishing)' == 'true'">
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Configuration" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Configuration.Abstractions" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Configuration.Binder" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Configuration.CommandLine" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Configuration.FileExtensions" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Configuration.Json" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Configuration.UserSecrets" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.DependencyInjection" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Diagnostics" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Diagnostics.Abstractions" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.FileProviders.Abstractions" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.FileProviders.Physical" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.FileSystemGlobbing" />
        <PackageVersion Version="10.0.10" Update="Microsoft.Extensions.Hosting" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Hosting.Abstractions" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Logging" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Logging.Configuration" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Logging.Console" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Logging.Debug" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Logging.EventLog" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Logging.EventSource" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Options" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
        <PackageVersion Version="10.0.10" Include="Microsoft.Extensions.Primitives" />
        <PackageVersion Version="10.0.10" Include="System.Diagnostics.EventLog" />
    </ItemGroup>
</Project>